name: Reusable Pipeline Orchestrator

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      helm_app_name:
        required: false
        type: string
    secrets:
      PAT_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SNYK_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      GMAIL_USERNAME:
        required: false
      GMAIL_APP_PASSWORD:
        required: false
      NOTIFY_EMAIL_TO:
        required: false

jobs:
  sonarcheck:
    name: sonarcheck
    permissions:
      contents: read
      security-events: write
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/sonarcheck.yaml@main
    with:
      image_name: ${{ inputs.image_name }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL_TO: ${{ secrets.NOTIFY_EMAIL_TO }}

  snykcheck:
    name: snykcheck
    needs: sonarcheck
    permissions:
      contents: read
      security-events: write
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/snykcheck.yaml@main
    with:
      image_name: ${{ inputs.image_name }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL_TO: ${{ secrets.NOTIFY_EMAIL_TO }}

  ci-build:
    name: ci-build
    needs: [sonarcheck, snykcheck]
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/ci-build.yaml@main
    with:
      image_name: ${{ inputs.image_name }}
      helm_app_name: ${{ inputs.helm_app_name }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL_TO: ${{ secrets.NOTIFY_EMAIL_TO }}
